
BASE:
  # log等级
  log_level: 'debug'
  #扩展名
  log_extension: ".log"
  test:
    url: "http://211.103.136.242:8064"
    case_file: "testdata.xlsx"
    case_sheet: "美多商城接口测试"


email:
  smtpserver: "mail.beeplay123.com"
  username: "zhangfajin@beeplay123.com"
  password: "20A36#20dugu2036"
  sender: "zhangfajin@beeplay123.com"
  to_receiver:  'huiselanse@yeah.net'
  cc_receiver: 'zhangfajin@beeplay123.com'
